[network]
listen_port = 8888
max_connections = 10000
ssl_enabled = true
ssl_cert = "/etc/ssl/moba/moba_gateway.crt"
ssl_key = "/etc/ssl/moba/moba_gateway.key"

[database]
mysql_host = "db.moba.com"
mysql_port = 3306
mysql_user = "moba_gateway"
mysql_password = "SecurePass123!"
mysql_dbname = "moba_main"

[redis]
host = "127.0.0.1"
port = 6379
password = "123456"
db_index = 1  # 逻辑服专用DB
pool_size = 20  # 连接池大小

[log]
path = "../logs/gateway.log"  # 支持绝对路径或相对路径
level = "debug"                     # 日志级别
max_size = "500MB"                  # 单文件最大尺寸
backup_count = 5                    # 保留历史文件数量
daemon_mode = true                  # 是否后台运行

[cluster]
logic_servers = [
    "192.168.1.101:8889",
    "192.168.1.102:8889",
    "192.168.1.103:8889"
]

[security]
rate_limit = 1000  # 每秒最大请求数
blacklist_expire = 3600  # 封禁时长(秒)

# 心跳检测配置
[heartbeat]
timeout = 30  # 客户端超时时间(秒)
check_interval = 5  # 检测间隔(秒)