[core]
frame_rate = 30  # 帧同步频率(Hz)
max_prediction = 3  # 最大预测帧数
physics_accuracy = 2  # 物理计算精度(1-3)

[network]
udp_port = 8889  # 帧同步UDP端口
broadcast_interval = 33  # 广播间隔(ms)

[redis]
host = "127.0.0.1"
port = 6379
password = "123456"
db_index = 1  # 逻辑服专用DB
pool_size = 20  # 连接池大小

[physics]
gravity = 9.81  # 重力加速度
collision_iterations = 5  # 碰撞检测迭代次数
movement_threshold = 0.001  # 移动判定阈值

[log]
path = "../logs/gateway.log"  # 支持绝对路径或相对路径
level = "debug"                     # 日志级别
max_size = "500MB"                  # 单文件最大尺寸
backup_count = 5                    # 保留历史文件数量
daemon_mode = true                  # 是否后台运行

[gateway]
gateway_ip = 127.0.0.1
gateway_port = 8888