[core]
frame_rate = 30  # 帧同步频率(Hz)
max_prediction = 3  # 最大预测帧数
physics_accuracy = 2  # 物理计算精度(1-3)

[network]
udp_port = 8889  # 帧同步UDP端口
broadcast_interval = 33  # 广播间隔(ms)

[redis]
host = "127.0.0.1"
port = 6379
password = "123456"
db_index = 1  # 逻辑服专用DB
pool_size = 20  # 连接池大小

[physics]
gravity = 9.81  # 重力加速度
collision_iterations = 5  # 碰撞检测迭代次数
movement_threshold = 0.001  # 移动判定阈值

[log]
level = "info"
path = "/var/log/moba/logic.log"
rotation_size = "50MB"

# 调试配置
[debug]
allow_cheat_codes = false  # 是否允许作弊码
log_missed_frames = true   # 记录丢帧情况